### ISSUE TITLE
Dropdown menu doesn't reset after going home

### ISSUE THREAD

**Issue by Shuggatank** [jassiejai/Wayfarer#16]
The dropdown menu does clear its selection after you go home/root.
![Screenshot 2022-02-16 at 06-26-00 Wayfarer](https://user-images.githubusercontent.com/61331819/154285016-2018245f-76de-40ad-af86-61a5b10dd558.png)

**Comment by juliobarriga** [comment]
I made a quick fix by accessing the element directly in a function every time we clicked home or set the URL to home.
Pushing the changes now.
