### ISSUE TITLE
Weather API is getting the weather for cities in the US.

### ISSUE THREAD

**Issue by juliobarriga** [jassiejai/Wayfarer#26]
the API is using the right name but in the wrong country, for example London is getting the weather from a city called London in the US, to fix this we need to find a way to add the country code to the weather API.
According to the documentation, we also need the state API, 
`api.openweathermap.org/data/2.5/weather?q={city name},{state code},{country code}&appid={API key}
or we can use a city ID, we can find the id on the documentation as well.

**Comment by Shuggatank** [comment]
https://api.openweathermap.org/data/2.5/weather?q=London,GB&appid=052f26926ae9784c2d677ca7bc5dec98
This gives the data for London, Great Britain. The temp is giving in Kelvin. May need to use the conversion formula to get Fahrenheit `°F =(K - 273.15)* 1.8000+ 32.00`

**Comment by Shuggatank** [comment]
https://openweathermap.org/weather-conditions
https://openweathermap.org/current#current_JSON

**Comment by Shuggatank** [comment]
https://api.openweathermap.org/data/2.5/weather?q=London,GB&units=metric&appid=052f26926ae9784c2d677ca7bc5dec98

`units=metric` will give Fahrenheit

**Comment by juliobarriga** [comment]
nice, I didn't see the icons before, I'm going to see how to implement them.
actually `units=metric` gives Celsius `units=imperial` gives Fahrenheit
so I guess this is the right API address we need to call then `http://api.openweathermap.org/data/2.5/weather?q=${cityName},${countryCode}&appid=052f26926ae9784c2d677ca7bc5dec98&&units=imperial`

**Comment by Shuggatank** [comment]
Right, it's imperial, my mistake. The API you posted works. Works for the US too
`https://api.openweathermap.org/data/2.5/weather?q=San%20Francisco,US&appid=052f26926ae9784c2d677ca7bc5dec98&&units=imperial` but looks like you need spaces for the name, so I added %20 for space.

**Comment by juliobarriga** [comment]
Thank you, looks like it's working now, I'm pushing the changes.
