### ISSUE TITLE
London pulling 2 weather calls

### ISSUE THREAD

**Issue by Shuggatank** [jassiejai/Wayfarer#30]
When selecting London it is making 2 API calls, one to San Francisco and one to London
![2022-02-17_06-58](https://user-images.githubusercontent.com/61331819/154508859-152e1af9-c89f-41a8-a5a9-8fc638c04555.png)

**Comment by juliobarriga** [comment]
fixed it by adding a conditional, also removed unnecessary code between nav component and cities.service.
Also, added an *ngIf=weather in the HTML to remove error we were getting after we called any city.
